name       : libxft
version    : 2.3.3
release    : 9
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXft-2.3.3.tar.gz : 3c3cf88b1a96e49a3d87d67d9452d34b6e25e96ae83959b8d0a980935014d701
license    :
    - MIT
summary    : FreeType-based font drawing library for X
component  : xorg.library
description: |
    Xft provides a client-side font API for X applications, making the FreeType
    font rasterizer available to X clients.  Fontconfig is used for font
    specification resolution.  Where available, the RENDER extension handles
    glyph drawing; otherwise, the core X protocol is used.
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(xrender)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
